--
-- PostgreSQL database dump
--

--\restrict ECmxL8g0Vy0xRBhAu0vkmUK5ujgjUr7eZ9KDqPd1e5Ooei8ys0DDpPW4166yVLM

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: appuser
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO appuser;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: appuser
--

COMMENT ON SCHEMA public IS '';


--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_movements; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.account_movements (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    transaction_number character varying(50) NOT NULL,
    account_id uuid NOT NULL,
    movement_type_id integer NOT NULL,
    amount numeric(18,2) NOT NULL,
    description character varying(255),
    status_id integer NOT NULL,
    created_by character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_by character varying(100),
    updated_at timestamp with time zone,
    CONSTRAINT account_movements_amount_ck CHECK ((amount > (0)::numeric))
);


ALTER TABLE public.account_movements OWNER TO appuser;

--
-- Name: account_status; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.account_status (
    id integer NOT NULL,
    code character varying(20) NOT NULL,
    description character varying(100) NOT NULL
);


ALTER TABLE public.account_status OWNER TO appuser;

--
-- Name: account_status_id_seq; Type: SEQUENCE; Schema: public; Owner: appuser
--

ALTER TABLE public.account_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_type; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.account_type (
    id integer NOT NULL,
    code character varying(30) NOT NULL,
    description character varying(100) NOT NULL
);


ALTER TABLE public.account_type OWNER TO appuser;

--
-- Name: account_type_id_seq; Type: SEQUENCE; Schema: public; Owner: appuser
--

ALTER TABLE public.account_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: business_rules; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.business_rules (
    code character varying(80) NOT NULL,
    subcode character varying(100) NOT NULL,
    description character varying(200) NOT NULL,
    active boolean DEFAULT false NOT NULL,
    severity smallint DEFAULT 1 NOT NULL,
    expression_sql text,
    created_by character varying(100),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_by character varying(100),
    updated_at timestamp with time zone
);


ALTER TABLE public.business_rules OWNER TO appuser;

--
-- Name: currency; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.currency (
    id integer NOT NULL,
    code character(3) NOT NULL,
    name character varying(50) NOT NULL,
    symbol character varying(5) NOT NULL
);


ALTER TABLE public.currency OWNER TO appuser;

--
-- Name: currency_id_seq; Type: SEQUENCE; Schema: public; Owner: appuser
--

ALTER TABLE public.currency ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.currency_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: deposit_account; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.deposit_account (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    account_number character varying(50) NOT NULL,
    person_id uuid NOT NULL,
    account_type_id integer NOT NULL,
    currency_id integer DEFAULT 1 NOT NULL,
    status_id integer DEFAULT 1 NOT NULL,
    total_balance numeric(18,2) DEFAULT 0 NOT NULL,
    total_blocked numeric(18,2) DEFAULT 0 NOT NULL,
    total_garnished numeric(18,2) DEFAULT 0 NOT NULL,
    total_available numeric(18,2) DEFAULT 0 NOT NULL,
    CONSTRAINT deposit_account_balance_ck CHECK (((total_balance >= (0)::numeric) AND (total_blocked >= (0)::numeric) AND (total_garnished >= (0)::numeric) AND (total_available >= (0)::numeric)))
);


ALTER TABLE public.deposit_account OWNER TO appuser;

--
-- Name: legal_entity_type; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.legal_entity_type (
    id integer NOT NULL,
    code character varying(30) NOT NULL,
    description character varying(100) NOT NULL
);


ALTER TABLE public.legal_entity_type OWNER TO appuser;

--
-- Name: legal_entity_type_id_seq; Type: SEQUENCE; Schema: public; Owner: appuser
--

ALTER TABLE public.legal_entity_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.legal_entity_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: legal_persons; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.legal_persons (
    person_id uuid NOT NULL,
    legal_name character varying(200) NOT NULL,
    incorporation_date date NOT NULL,
    legal_entity_type_id integer NOT NULL,
    CONSTRAINT legal_persons_incorporation_date_ck CHECK ((incorporation_date <= CURRENT_DATE))
);


ALTER TABLE public.legal_persons OWNER TO appuser;

--
-- Name: movement_status; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.movement_status (
    id integer NOT NULL,
    code character varying(20) NOT NULL,
    description character varying(100) NOT NULL
);


ALTER TABLE public.movement_status OWNER TO appuser;

--
-- Name: movement_status_id_seq; Type: SEQUENCE; Schema: public; Owner: appuser
--

ALTER TABLE public.movement_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movement_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movement_type; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.movement_type (
    id integer NOT NULL,
    code character varying(30) NOT NULL,
    description character varying(150) NOT NULL,
    total_balance_sign smallint DEFAULT 0 NOT NULL,
    blocked_sign smallint DEFAULT 0 NOT NULL,
    garnished_sign smallint DEFAULT 0 NOT NULL,
    requires_counterparty boolean DEFAULT false NOT NULL,
    CONSTRAINT movement_type_signs_ck CHECK (((total_balance_sign = ANY (ARRAY['-1'::integer, 0, 1])) AND (blocked_sign = ANY (ARRAY['-1'::integer, 0, 1])) AND (garnished_sign = ANY (ARRAY['-1'::integer, 0, 1]))))
);


ALTER TABLE public.movement_type OWNER TO appuser;

--
-- Name: movement_type_id_seq; Type: SEQUENCE; Schema: public; Owner: appuser
--

ALTER TABLE public.movement_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movement_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: natural_persons; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.natural_persons (
    person_id uuid NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    birth_date date,
    CONSTRAINT natural_persons_birth_date_ck CHECK (((birth_date IS NULL) OR (birth_date <= CURRENT_DATE)))
);


ALTER TABLE public.natural_persons OWNER TO appuser;

--
-- Name: person_type; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.person_type (
    id integer NOT NULL,
    code character varying(10) NOT NULL,
    description character varying(50) NOT NULL
);


ALTER TABLE public.person_type OWNER TO appuser;

--
-- Name: person_type_id_seq; Type: SEQUENCE; Schema: public; Owner: appuser
--

ALTER TABLE public.person_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.person_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: persons; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.persons (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    person_type_id integer NOT NULL,
    display_name character varying(200) NOT NULL
);


ALTER TABLE public.persons OWNER TO appuser;

--
-- Data for Name: account_movements; Type: TABLE DATA; Schema: public; Owner: appuser
--

COPY public.account_movements (id, transaction_number, account_id, movement_type_id, amount, description, status_id, created_by, created_at, updated_by, updated_at) FROM stdin;
\.


--
-- Data for Name: account_status; Type: TABLE DATA; Schema: public; Owner: appuser
--

COPY public.account_status (id, code, description) FROM stdin;
1	PENDING	Cuenta creada, pendiente de aprobación
2	ACTIVE	Cuenta activa
3	BLOCKED	Cuenta bloqueada
4	GARNISHED	Cuenta embargada
5	CLOSED	Cuenta cerrada definitivamente
\.


--
-- Data for Name: account_type; Type: TABLE DATA; Schema: public; Owner: appuser
--

COPY public.account_type (id, code, description) FROM stdin;
1	SAVINGS	Cuenta de ahorro
2	CHECKING	Cuenta corriente
\.


--
-- Data for Name: business_rules; Type: TABLE DATA; Schema: public; Owner: appuser
--

COPY public.business_rules (code, subcode, description, active, severity, expression_sql, created_by, created_at, updated_by, updated_at) FROM stdin;
\.


--
-- Data for Name: currency; Type: TABLE DATA; Schema: public; Owner: appuser
--

COPY public.currency (id, code, name, symbol) FROM stdin;
1	BOB	Boliviano	Bs
2	USD	Dólar estadounidense	$
\.


--
-- Data for Name: deposit_account; Type: TABLE DATA; Schema: public; Owner: appuser
--

COPY public.deposit_account (id, person_id, account_type_id, currency_id, status_id, account_number, total_balance, total_blocked, total_garnished, total_available) FROM stdin;
\.


--
-- Data for Name: legal_entity_type; Type: TABLE DATA; Schema: public; Owner: appuser
--

COPY public.legal_entity_type (id, code, description) FROM stdin;
1	SA	Sociedad Anónima
2	SRL	Sociedad de Responsabilidad Limitada
3	ONG	Organización No Gubernamental
\.


--
-- Data for Name: legal_persons; Type: TABLE DATA; Schema: public; Owner: appuser
--

COPY public.legal_persons (person_id, legal_name, incorporation_date, legal_entity_type_id) FROM stdin;
\.


--
-- Data for Name: movement_status; Type: TABLE DATA; Schema: public; Owner: appuser
--

COPY public.movement_status (id, code, description) FROM stdin;
1	PENDING	Movimiento registrado, aún no aplicado al saldo
2	APPLIED	Movimiento aplicado al saldo
3	REVERSED	Movimiento revertido
4	FAILED	Movimiento rechazado
\.


--
-- Data for Name: movement_type; Type: TABLE DATA; Schema: public; Owner: appuser
--

COPY public.movement_type (id, code, description, total_balance_sign, blocked_sign, garnished_sign, requires_counterparty) FROM stdin;
1	DEPOSIT	Depósito	1	0	0	f
2	WITHDRAWAL	Retiro	-1	0	0	f
3	TRANSFER_IN	Transferencia recibida	1	0	0	t
4	TRANSFER_OUT	Transferencia enviada	-1	0	0	t
5	BLOCK	Bloqueo de fondos	0	1	0	f
6	UNBLOCK	Desbloqueo de fondos	0	-1	0	f
7	GARNISHMENT	Retención judicial	0	0	1	f
8	GARNISHMENT_RELEASE	Liberación de retención judicial	0	0	-1	f
\.


--
-- Data for Name: natural_persons; Type: TABLE DATA; Schema: public; Owner: appuser
--

COPY public.natural_persons (person_id, first_name, last_name, birth_date) FROM stdin;
\.


--
-- Data for Name: person_type; Type: TABLE DATA; Schema: public; Owner: appuser
--

COPY public.person_type (id, code, description) FROM stdin;
1	NATURAL	Persona natural
2	LEGAL	Persona jurídica
\.


--
-- Data for Name: persons; Type: TABLE DATA; Schema: public; Owner: appuser
--

COPY public.persons (id, person_type_id, display_name) FROM stdin;
\.


--
-- Name: account_status_id_seq; Type: SEQUENCE SET; Schema: public; Owner: appuser
--

SELECT pg_catalog.setval('public.account_status_id_seq', 1, false);


--
-- Name: account_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: appuser
--

SELECT pg_catalog.setval('public.account_type_id_seq', 1, false);


--
-- Name: currency_id_seq; Type: SEQUENCE SET; Schema: public; Owner: appuser
--

SELECT pg_catalog.setval('public.currency_id_seq', 1, false);


--
-- Name: legal_entity_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: appuser
--

SELECT pg_catalog.setval('public.legal_entity_type_id_seq', 1, false);


--
-- Name: movement_status_id_seq; Type: SEQUENCE SET; Schema: public; Owner: appuser
--

SELECT pg_catalog.setval('public.movement_status_id_seq', 1, false);


--
-- Name: movement_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: appuser
--

SELECT pg_catalog.setval('public.movement_type_id_seq', 1, false);


--
-- Name: person_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: appuser
--

SELECT pg_catalog.setval('public.person_type_id_seq', 1, false);


--
-- Name: account_movements account_movements_pkey; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.account_movements
    ADD CONSTRAINT account_movements_pkey PRIMARY KEY (id);


--
-- Name: account_movements account_movements_transaction_number_key; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.account_movements
    ADD CONSTRAINT account_movements_transaction_number_key UNIQUE (transaction_number);


--
-- Name: account_status account_status_code_key; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.account_status
    ADD CONSTRAINT account_status_code_key UNIQUE (code);


--
-- Name: account_status account_status_pkey; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.account_status
    ADD CONSTRAINT account_status_pkey PRIMARY KEY (id);


--
-- Name: account_type account_type_code_key; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.account_type
    ADD CONSTRAINT account_type_code_key UNIQUE (code);


--
-- Name: account_type account_type_pkey; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.account_type
    ADD CONSTRAINT account_type_pkey PRIMARY KEY (id);


--
-- Name: business_rules business_rules_pk; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.business_rules
    ADD CONSTRAINT business_rules_pk PRIMARY KEY (code, subcode);


--
-- Name: currency currency_code_key; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.currency
    ADD CONSTRAINT currency_code_key UNIQUE (code);


--
-- Name: currency currency_pkey; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.currency
    ADD CONSTRAINT currency_pkey PRIMARY KEY (id);


--
-- Name: deposit_account deposit_account_account_number_key; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.deposit_account
    ADD CONSTRAINT deposit_account_account_number_key UNIQUE (account_number);


--
-- Name: deposit_account deposit_account_pkey; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.deposit_account
    ADD CONSTRAINT deposit_account_pkey PRIMARY KEY (id);


--
-- Name: legal_entity_type legal_entity_type_code_key; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.legal_entity_type
    ADD CONSTRAINT legal_entity_type_code_key UNIQUE (code);


--
-- Name: legal_entity_type legal_entity_type_pkey; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.legal_entity_type
    ADD CONSTRAINT legal_entity_type_pkey PRIMARY KEY (id);


--
-- Name: legal_persons legal_persons_pkey; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.legal_persons
    ADD CONSTRAINT legal_persons_pkey PRIMARY KEY (person_id);


--
-- Name: movement_status movement_status_code_key; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.movement_status
    ADD CONSTRAINT movement_status_code_key UNIQUE (code);


--
-- Name: movement_status movement_status_pkey; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.movement_status
    ADD CONSTRAINT movement_status_pkey PRIMARY KEY (id);


--
-- Name: movement_type movement_type_code_key; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.movement_type
    ADD CONSTRAINT movement_type_code_key UNIQUE (code);


--
-- Name: movement_type movement_type_pkey; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.movement_type
    ADD CONSTRAINT movement_type_pkey PRIMARY KEY (id);


--
-- Name: natural_persons natural_persons_pkey; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.natural_persons
    ADD CONSTRAINT natural_persons_pkey PRIMARY KEY (person_id);


--
-- Name: person_type person_type_code_key; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.person_type
    ADD CONSTRAINT person_type_code_key UNIQUE (code);


--
-- Name: person_type person_type_pkey; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.person_type
    ADD CONSTRAINT person_type_pkey PRIMARY KEY (id);


--
-- Name: persons persons_pkey; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.persons
    ADD CONSTRAINT persons_pkey PRIMARY KEY (id);


--
-- Name: idx_account_movements_account_created_at; Type: INDEX; Schema: public; Owner: appuser
--

CREATE INDEX idx_account_movements_account_created_at ON public.account_movements USING btree (account_id, created_at DESC);


--
-- Name: idx_account_movements_movement_type_id; Type: INDEX; Schema: public; Owner: appuser
--

CREATE INDEX idx_account_movements_movement_type_id ON public.account_movements USING btree (movement_type_id);


--
-- Name: idx_account_movements_status_id; Type: INDEX; Schema: public; Owner: appuser
--

CREATE INDEX idx_account_movements_status_id ON public.account_movements USING btree (status_id);


--
-- Name: idx_deposit_account_account_type_id; Type: INDEX; Schema: public; Owner: appuser
--

CREATE INDEX idx_deposit_account_account_type_id ON public.deposit_account USING btree (account_type_id);


--
-- Name: idx_deposit_account_person_id; Type: INDEX; Schema: public; Owner: appuser
--

CREATE INDEX idx_deposit_account_person_id ON public.deposit_account USING btree (person_id);


--
-- Name: idx_deposit_account_status_id; Type: INDEX; Schema: public; Owner: appuser
--

CREATE INDEX idx_deposit_account_status_id ON public.deposit_account USING btree (status_id);


--
-- Name: idx_persons_person_type_id; Type: INDEX; Schema: public; Owner: appuser
--

CREATE INDEX idx_persons_person_type_id ON public.persons USING btree (person_type_id);


--
-- Name: account_movements account_movements_account_fk; Type: FK CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.account_movements
    ADD CONSTRAINT account_movements_account_fk FOREIGN KEY (account_id) REFERENCES public.deposit_account(id) ON DELETE RESTRICT;


--
-- Name: account_movements account_movements_status_fk; Type: FK CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.account_movements
    ADD CONSTRAINT account_movements_status_fk FOREIGN KEY (status_id) REFERENCES public.movement_status(id) ON DELETE RESTRICT;


--
-- Name: account_movements account_movements_type_fk; Type: FK CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.account_movements
    ADD CONSTRAINT account_movements_type_fk FOREIGN KEY (movement_type_id) REFERENCES public.movement_type(id) ON DELETE RESTRICT;


--
-- Name: deposit_account deposit_account_account_type_fk; Type: FK CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.deposit_account
    ADD CONSTRAINT deposit_account_account_type_fk FOREIGN KEY (account_type_id) REFERENCES public.account_type(id) ON DELETE RESTRICT;


--
-- Name: deposit_account deposit_account_currency_fk; Type: FK CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.deposit_account
    ADD CONSTRAINT deposit_account_currency_fk FOREIGN KEY (currency_id) REFERENCES public.currency(id) ON DELETE RESTRICT;


--
-- Name: deposit_account deposit_account_person_fk; Type: FK CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.deposit_account
    ADD CONSTRAINT deposit_account_person_fk FOREIGN KEY (person_id) REFERENCES public.persons(id) ON DELETE RESTRICT;


--
-- Name: deposit_account deposit_account_status_fk; Type: FK CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.deposit_account
    ADD CONSTRAINT deposit_account_status_fk FOREIGN KEY (status_id) REFERENCES public.account_status(id) ON DELETE RESTRICT;


--
-- Name: legal_persons legal_persons_person_fk; Type: FK CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.legal_persons
    ADD CONSTRAINT legal_persons_person_fk FOREIGN KEY (person_id) REFERENCES public.persons(id) ON DELETE CASCADE;


--
-- Name: legal_persons legal_persons_type_fk; Type: FK CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.legal_persons
    ADD CONSTRAINT legal_persons_type_fk FOREIGN KEY (legal_entity_type_id) REFERENCES public.legal_entity_type(id) ON DELETE RESTRICT;


--
-- Name: natural_persons natural_persons_person_fk; Type: FK CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.natural_persons
    ADD CONSTRAINT natural_persons_person_fk FOREIGN KEY (person_id) REFERENCES public.persons(id) ON DELETE CASCADE;


--
-- Name: persons persons_person_type_fk; Type: FK CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.persons
    ADD CONSTRAINT persons_person_type_fk FOREIGN KEY (person_type_id) REFERENCES public.person_type(id) ON DELETE RESTRICT;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: appuser
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- PostgreSQL database dump complete
--

--\unrestrict ECmxL8g0Vy0xRBhAu0vkmUK5ujgjUr7eZ9KDqPd1e5Ooei8ys0DDpPW4166yVLM

